### ISSUE TITLE
Check Windows and MacOS Builds

### ISSUE THREAD

**Issue by MarventusWP** [terra-rebels/station-desktop#1]
**Task Fundamentals:**
WHAT: Ensure the app builds for both Windows,Mac OS X and Linux.
WHY: Support the same desktop platforms than the original app.

**Tasks:**
- [ ] Check that the build works for Windows.
- [ ] Check that the build works for Mac OS X.
- [ ] Check that the build works for Linux.

**Acceptance criteria:**
- [ ] Succesful Windows build
- [ ] Succesful Mac OS X build
- [ ] Succesful Linux build
